spring:
  datasource:
    url: jdbc:h2:mem:batch;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  batch:
    initialize-schema: always
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop

